### ISSUE TITLE
dotnet8 support!

### ISSUE THREAD

**Issue by naratteu** [LostBeard/BlazorWASMScriptLoader#1]
I tried changing the target framework of the example to .NET 8, updating NuGet packages, and modifying the file path for dynamic loading. However, I couldn't get it to work as before.

Would it be possible for you to modify the example so that it works on .NET 8?

**Comment by LostBeard** [comment]
The problem is that Blazor WASM .Net 8 switched to using .wasm files instead of .dll files. I am unable to get a usable MetadataReference from an Assembly using the .wasm files or any other source available in a .Net 8 Blazor WASM app. 

Failure error:  
```CS0009: Metadata file '<in-memory assembly>' could not be opened -- PE image doesn't contain managed metadata.```

**Comment by LostBeard** [comment]
I found a fix. You can switch the build back to using ".dll" extensions by adding ```<WasmEnableWebcil>false</WasmEnableWebcil>``` to a PropertyGroup in  your prject .csproj. Then the code works.

Modify your .Net 8 project .csproj 
```xml
<PropertyGroup>
    <WasmEnableWebcil>false</WasmEnableWebcil>
</PropertyGroup>
```

**Comment by LostBeard** [comment]
```<WasmEnableWebcil>``` Flag reference: [Webcil packaging format for .NET assemblies
](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-8.0#webcil-packaging-format-for-net-assemblies)

**Comment by naratteu** [comment]
yes It works fine! Thank you so much for helping me.
